# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title 
safe: true # Google Analytics

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : srea.github.io
tagline: Site Tagline
author :
  name : Yuki Tamazawa
  email : yuki.tamazawa@icloud.com 
  github : srea
  twitter : yukimikan88 
  feedburner : feedname

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://srea.github.io
theme: jekyll-theme-cayman
gems:
    - jemoji
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
