title: srea 
email: srea@minipro.co 
description: >- # this means to ignore newlines until "baseurl:"
    less is more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://srea.github.io"
timezone: Asia/Tokyo
twitter_username: yukimikan88
github_username:  srea
facebook_username: srea.jp
instagram_username: yukimikan88
header_pages:
  - about.md
  - apps.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-admin
  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
